on: [push, pull_request]

jobs:
  windows:
    uses: rime/librime/.github/workflows/windows-build.yml@master
    with:
      repository: rime/librime
      rime_plugins: ${{ github.repository }}@${{ github.ref_name }} rime/librime-charcode lotem/librime-octagram
